/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#include "xenia/cpu/testing/util.h"

#include <cstdint>
#include <cstring>

using namespace xe::cpu::hir;
using namespace xe::cpu;
using namespace xe::cpu::testing;
using xe::cpu::ppc::PPCContext;

namespace {

enum class FpOp { kAdd, kSub, kMul, kDiv };

bool IsNaN(uint64_t bits) {
  return (bits & 0x7FF0000000000000ull) == 0x7FF0000000000000ull &&
         (bits & 0x000FFFFFFFFFFFFFull) != 0;
}

// PowerPC: the first NaN operand wins and is quieted; a NaN generated by the
// operation itself is the default QNaN (as in the fadd/fmul golden tests).
uint64_t Reference(uint64_t a_bits, uint64_t b_bits, FpOp op) {
  if (IsNaN(a_bits)) {
    return a_bits | (1ull << 51);
  }
  if (IsNaN(b_bits)) {
    return b_bits | (1ull << 51);
  }
  double a, b, r = 0.0;
  std::memcpy(&a, &a_bits, sizeof(a));
  std::memcpy(&b, &b_bits, sizeof(b));
  switch (op) {
    case FpOp::kAdd:
      r = a + b;
      break;
    case FpOp::kSub:
      r = a - b;
      break;
    case FpOp::kMul:
      r = a * b;
      break;
    case FpOp::kDiv:
      r = a / b;
      break;
  }
  uint64_t r_bits;
  std::memcpy(&r_bits, &r, sizeof(r_bits));
  return IsNaN(r_bits) ? 0x7FF8000000000000ull : r_bits;
}

void RunMatrix(FpOp op) {
  static const uint64_t kValues[] = {
      0x7FF8000000000001ull,  // +QNaN
      0xFFF8000000000001ull,  // -QNaN
      0x7FF0000000000001ull,  // +SNaN
      0xFFF0000000000001ull,  // -SNaN
      0x7FF0000000000000ull,  // +inf
      0xFFF0000000000000ull,  // -inf
      0x0000000000000000ull,  // +0
      0x8000000000000000ull,  // -0
      0x3FF0000000000000ull,  // 1.0
      0xC004000000000000ull,  // -2.5
      0x0000000000000001ull,  // +denormal
      0x7FEFFFFFFFFFFFFFull,  // max
  };
  TestFunction test([op](HIRBuilder& b) {
    Value* a = LoadFPR(b, 1);
    Value* c = LoadFPR(b, 2);
    Value* r = nullptr;
    switch (op) {
      case FpOp::kAdd:
        r = b.Add(a, c);
        break;
      case FpOp::kSub:
        r = b.Sub(a, c);
        break;
      case FpOp::kMul:
        r = b.Mul(a, c);
        break;
      case FpOp::kDiv:
        r = b.Div(a, c);
        break;
    }
    StoreFPR(b, 3, r);
    b.Return();
  });
  for (uint64_t a : kValues) {
    for (uint64_t c : kValues) {
      INFO("a 0x" << std::hex << a << " b 0x" << c);
      test.Run(
          [&](PPCContext* ctx) {
            std::memcpy(&ctx->f[1], &a, sizeof(a));
            std::memcpy(&ctx->f[2], &c, sizeof(c));
          },
          [&](PPCContext* ctx) {
            uint64_t result;
            std::memcpy(&result, &ctx->f[3], sizeof(result));
            REQUIRE(result == Reference(a, c, op));
          });
    }
  }
}

}  // namespace

// The PPC golden corpus has no NaN operands for scalar arithmetic.
TEST_CASE("SCALAR_FP_NAN_ADD", "[instr]") { RunMatrix(FpOp::kAdd); }
TEST_CASE("SCALAR_FP_NAN_SUB", "[instr]") { RunMatrix(FpOp::kSub); }
TEST_CASE("SCALAR_FP_NAN_MUL", "[instr]") { RunMatrix(FpOp::kMul); }
TEST_CASE("SCALAR_FP_NAN_DIV", "[instr]") { RunMatrix(FpOp::kDiv); }
