/**
 ******************************************************************************
 * Xenia : Xbox 360 Emulator Research Project                                 *
 ******************************************************************************
 * Copyright 2026 Ben Vanik. All rights reserved.                             *
 * Released under the BSD license - see LICENSE in the root for more details. *
 ******************************************************************************
 */

#include "xenia/cpu/testing/util.h"

#include <cmath>
#include <cstdint>
#include <cstring>

using namespace xe::cpu::hir;
using namespace xe::cpu;
using namespace xe::cpu::testing;
using xe::cpu::ppc::PPCContext;

namespace {

enum class FpOp { kAdd, kSub, kMul, kDiv };

bool IsNaN(uint64_t bits) {
  return (bits & 0x7FF0000000000000ull) == 0x7FF0000000000000ull &&
         (bits & 0x000FFFFFFFFFFFFFull) != 0;
}

// PowerPC: the first NaN operand wins and is quieted; a NaN generated by the
// operation itself is the default QNaN (as in the fadd/fmul golden tests).
uint64_t Reference(uint64_t a_bits, uint64_t b_bits, FpOp op) {
  if (IsNaN(a_bits)) {
    return a_bits | (1ull << 51);
  }
  if (IsNaN(b_bits)) {
    return b_bits | (1ull << 51);
  }
  double a, b, r = 0.0;
  std::memcpy(&a, &a_bits, sizeof(a));
  std::memcpy(&b, &b_bits, sizeof(b));
  switch (op) {
    case FpOp::kAdd:
      r = a + b;
      break;
    case FpOp::kSub:
      r = a - b;
      break;
    case FpOp::kMul:
      r = a * b;
      break;
    case FpOp::kDiv:
      r = a / b;
      break;
  }
  uint64_t r_bits;
  std::memcpy(&r_bits, &r, sizeof(r_bits));
  return IsNaN(r_bits) ? 0x7FF8000000000000ull : r_bits;
}

const uint64_t kValues[] = {
    0x7FF8000000000001ull,  // +QNaN
    0xFFF8000000000001ull,  // -QNaN
    0x7FF0000000000001ull,  // +SNaN
    0xFFF0000000000001ull,  // -SNaN
    0x7FF0000000000000ull,  // +inf
    0xFFF0000000000000ull,  // -inf
    0x0000000000000000ull,  // +0
    0x8000000000000000ull,  // -0
    0x3FF0000000000000ull,  // 1.0
    0xC004000000000000ull,  // -2.5
    0x0000000000000001ull,  // +denormal
    0x7FEFFFFFFFFFFFFFull,  // max
};

uint64_t Quiet(uint64_t bits) {
  return IsNaN(bits) ? bits | (1ull << 51) : bits;
}

// Where the second operand comes from. The backend can leave the NaN rule to
// the hardware when the second operand is the first, or the result of
// arithmetic, which is never a signalling NaN.
enum class Second { kLoaded, kArithmetic, kFirst };

void RunMatrix(FpOp op, Second second = Second::kLoaded) {
  TestFunction test([op, second](HIRBuilder& b) {
    Value* a = LoadFPR(b, 1);
    Value* c = a;
    if (second == Second::kLoaded) {
      c = LoadFPR(b, 2);
    } else if (second == Second::kArithmetic) {
      c = b.Mul(LoadFPR(b, 2), b.LoadConstantFloat64(1.0));
    }
    Value* r = nullptr;
    switch (op) {
      case FpOp::kAdd:
        r = b.Add(a, c);
        break;
      case FpOp::kSub:
        r = b.Sub(a, c);
        break;
      case FpOp::kMul:
        r = b.Mul(a, c);
        break;
      case FpOp::kDiv:
        r = b.Div(a, c);
        break;
    }
    StoreFPR(b, 3, r);
    b.Return();
  });
  for (uint64_t a : kValues) {
    for (uint64_t c : kValues) {
      // Multiplying by one quiets a NaN and changes nothing else here: the
      // FPU mode does not flush denormals.
      const uint64_t second_bits = second == Second::kFirst        ? a
                                   : second == Second::kArithmetic ? Quiet(c)
                                                                   : c;
      INFO("a 0x" << std::hex << a << " b 0x" << c);
      test.Run(
          [&](PPCContext* ctx) {
            std::memcpy(&ctx->f[1], &a, sizeof(a));
            std::memcpy(&ctx->f[2], &c, sizeof(c));
          },
          [&](PPCContext* ctx) {
            uint64_t result;
            std::memcpy(&result, &ctx->f[3], sizeof(result));
            REQUIRE(result == Reference(a, second_bits, op));
          });
    }
  }
}

// PowerPC fmadd/fmsub and their negations: the first NaN of frA, frB, frC
// wins, quieted and not negated; a NaN the operation generates is the default
// QNaN, also not negated.
uint64_t FmaReference(uint64_t a_bits, uint64_t c_bits, uint64_t b_bits,
                      bool sub, bool negate) {
  for (uint64_t bits : {a_bits, b_bits, c_bits}) {
    if (IsNaN(bits)) {
      return Quiet(bits);
    }
  }
  double a, b, c;
  std::memcpy(&a, &a_bits, sizeof(a));
  std::memcpy(&b, &b_bits, sizeof(b));
  std::memcpy(&c, &c_bits, sizeof(c));
  // Through a volatile: the compiler may fold the negation below into the fma
  // as fnmadd or fnmsub, which negates the product and the addend separately
  // and gives the other zero when they are zeros of opposite sign.
  volatile double fused = std::fma(a, c, sub ? -b : b);
  const double r = fused;
  if (std::isnan(r)) {
    return 0x7FF8000000000000ull;
  }
  uint64_t r_bits;
  std::memcpy(&r_bits, &r, sizeof(r_bits));
  return negate ? r_bits ^ (1ull << 63) : r_bits;
}

void RunFmaMatrix(bool sub, bool negate) {
  TestFunction test([sub, negate](HIRBuilder& b) {
    Value* a = LoadFPR(b, 1);
    Value* c = LoadFPR(b, 2);
    Value* addend = LoadFPR(b, 3);
    Value* r =
        sub ? b.MulSub(a, c, addend, negate) : b.MulAdd(a, c, addend, negate);
    StoreFPR(b, 4, r);
    b.Return();
  });
  // Each operand's NaNs carry a payload of their own, so the result shows
  // which operand won.
  auto tag = [](uint64_t bits, uint64_t operand) {
    return IsNaN(bits) ? bits | (operand << 40) : bits;
  };
  for (uint64_t a0 : kValues) {
    for (uint64_t c0 : kValues) {
      for (uint64_t b0 : kValues) {
        const uint64_t a = tag(a0, 1), c = tag(c0, 2), addend = tag(b0, 3);
        INFO("a 0x" << std::hex << a << " c 0x" << c << " b 0x" << addend);
        test.Run(
            [&](PPCContext* ctx) {
              std::memcpy(&ctx->f[1], &a, sizeof(a));
              std::memcpy(&ctx->f[2], &c, sizeof(c));
              std::memcpy(&ctx->f[3], &addend, sizeof(addend));
            },
            [&](PPCContext* ctx) {
              uint64_t result;
              std::memcpy(&result, &ctx->f[4], sizeof(result));
              REQUIRE(result == FmaReference(a, c, addend, sub, negate));
            });
      }
    }
  }
}

}  // namespace

// The PPC golden corpus has no NaN operands for scalar arithmetic.
TEST_CASE("SCALAR_FP_NAN_ADD", "[instr]") { RunMatrix(FpOp::kAdd); }
TEST_CASE("SCALAR_FP_NAN_SUB", "[instr]") { RunMatrix(FpOp::kSub); }
TEST_CASE("SCALAR_FP_NAN_MUL", "[instr]") { RunMatrix(FpOp::kMul); }
TEST_CASE("SCALAR_FP_NAN_DIV", "[instr]") { RunMatrix(FpOp::kDiv); }
TEST_CASE("SCALAR_FP_NAN_ARITHMETIC_SECOND", "[instr]") {
  for (FpOp op : {FpOp::kAdd, FpOp::kSub, FpOp::kMul, FpOp::kDiv}) {
    RunMatrix(op, Second::kArithmetic);
  }
}
TEST_CASE("SCALAR_FP_NAN_SAME_OPERAND", "[instr]") {
  for (FpOp op : {FpOp::kAdd, FpOp::kSub, FpOp::kMul, FpOp::kDiv}) {
    RunMatrix(op, Second::kFirst);
  }
}
TEST_CASE("SCALAR_FP_NAN_MUL_ADD", "[instr]") { RunFmaMatrix(false, false); }
TEST_CASE("SCALAR_FP_NAN_MUL_SUB", "[instr]") { RunFmaMatrix(true, false); }
TEST_CASE("SCALAR_FP_NAN_NMUL_ADD", "[instr]") { RunFmaMatrix(false, true); }
TEST_CASE("SCALAR_FP_NAN_NMUL_SUB", "[instr]") { RunFmaMatrix(true, true); }
